from collections.abc import Sequence
from types import EllipsisType
from typing import ClassVar, Literal, ParamSpec, TypeVar, override

class ResolutionError(Exception): ...

class Qualifier:
    ANY: ClassVar[Qualifier]

    def __init__(self, *tags: str, _union: object | None = None) -> None: ...
    @property
    def alternatives(self) -> frozenset[frozenset[str]]: ...
    @property
    def is_qualified(self) -> bool: ...
    def __and__(self, other: Qualifier) -> Qualifier: ...
    def __or__(self, other: Qualifier) -> Qualifier: ...
    @override
    def __repr__(self) -> str: ...
    @override
    def __eq__(self, other: object) -> bool: ...
    @override
    def __hash__(self) -> int: ...

class SentinelType:
    def __init__(self, value: None | EllipsisType, qualifiers: Qualifier) -> None: ...
    @property
    def value(self) -> None | EllipsisType: ...
    @property
    def qualifiers(self) -> Qualifier: ...
    @override
    def __eq__(self, other: object) -> bool: ...
    @override
    def __repr__(self) -> str: ...

class TypeVarType:
    def __init__(self, typevar: TypeVar, qualifiers: Qualifier) -> None: ...
    @property
    def typevar(self) -> TypeVar: ...
    @property
    def qualifiers(self) -> Qualifier: ...
    @override
    def __eq__(self, other: object) -> bool: ...
    @override
    def __repr__(self) -> str: ...

class ParamSpecType:
    def __init__(self, paramspec: ParamSpec, qualifiers: Qualifier) -> None: ...
    @property
    def paramspec(self) -> ParamSpec: ...
    @property
    def qualifiers(self) -> Qualifier: ...
    @override
    def __eq__(self, other: object) -> bool: ...
    @override
    def __repr__(self) -> str: ...

class PlainType:
    def __init__(
        self,
        origin: type,
        args: tuple[NormalizedType, ...],
        qualifiers: Qualifier,
    ) -> None: ...
    @property
    def origin(self) -> type: ...
    @property
    def args(self) -> tuple[NormalizedType, ...]: ...
    @property
    def qualifiers(self) -> Qualifier: ...
    def _replace_child(self, old: object, new: NormalizedType) -> None: ...
    @override
    def __eq__(self, other: object) -> bool: ...
    @override
    def __repr__(self) -> str: ...

class ProtocolType:
    def __init__(
        self,
        origin: type,
        type_params: tuple[NormalizedType, ...],
        methods: dict[str, NormalizedType],
        attributes: dict[str, NormalizedType],
        properties: dict[str, NormalizedType],
        qualifiers: Qualifier,
    ) -> None: ...
    @property
    def origin(self) -> type: ...
    @property
    def type_params(self) -> tuple[NormalizedType, ...]: ...
    @property
    def methods(self) -> dict[str, NormalizedType]: ...
    @property
    def attributes(self) -> dict[str, NormalizedType]: ...
    @property
    def properties(self) -> dict[str, NormalizedType]: ...
    @property
    def qualifiers(self) -> Qualifier: ...
    def _replace_child(self, old: object, new: NormalizedType) -> None: ...
    @override
    def __eq__(self, other: object) -> bool: ...
    @override
    def __repr__(self) -> str: ...

class TypedDictType:
    def __init__(
        self,
        origin: type,
        type_params: tuple[NormalizedType, ...],
        attributes: dict[str, NormalizedType],
        qualifiers: Qualifier,
    ) -> None: ...
    @property
    def origin(self) -> type: ...
    @property
    def type_params(self) -> tuple[NormalizedType, ...]: ...
    @property
    def attributes(self) -> dict[str, NormalizedType]: ...
    @property
    def qualifiers(self) -> Qualifier: ...
    def _replace_child(self, old: object, new: NormalizedType) -> None: ...
    @override
    def __eq__(self, other: object) -> bool: ...
    @override
    def __repr__(self) -> str: ...

class UnionType:
    def __init__(
        self,
        variants: tuple[NormalizedType, ...],
        qualifiers: Qualifier,
    ) -> None: ...
    @property
    def variants(self) -> tuple[NormalizedType, ...]: ...
    @property
    def qualifiers(self) -> Qualifier: ...
    def _replace_child(self, old: object, new: NormalizedType) -> None: ...
    @override
    def __eq__(self, other: object) -> bool: ...
    @override
    def __repr__(self) -> str: ...

type WrapperKind = Literal[
    'none', 'awaitable', 'context_manager', 'async_context_manager'
]

type ParamKind = Literal['positional_only', 'positional_or_keyword', 'keyword_only']

class CallableType:
    def __init__(
        self,
        params: tuple[NormalizedType, ...],
        param_names: tuple[str, ...],
        param_kinds: tuple[ParamKind, ...],
        return_type: NormalizedType,
        return_wrapper: WrapperKind,
        type_params: tuple[NormalizedType, ...],
        qualifiers: Qualifier,
        function_name: str | None = None,
        param_has_default: Sequence[bool] | None = None,
        param_context_inject: Sequence[bool] | None = None,
        accepts_varargs: bool = False,
        accepts_varkw: bool = False,
    ) -> None: ...
    @property
    def params(self) -> tuple[NormalizedType, ...]: ...
    @property
    def param_names(self) -> tuple[str, ...]: ...
    @property
    def param_kinds(self) -> tuple[ParamKind, ...]: ...
    @property
    def return_type(self) -> NormalizedType: ...
    @property
    def return_wrapper(self) -> WrapperKind: ...
    @property
    def type_params(self) -> tuple[NormalizedType, ...]: ...
    @property
    def qualifiers(self) -> Qualifier: ...
    @property
    def function_name(self) -> str | None: ...
    @property
    def accepts_varargs(self) -> bool: ...
    @property
    def accepts_varkw(self) -> bool: ...
    def _replace_child(self, old: object, new: NormalizedType) -> None: ...
    @override
    def __eq__(self, other: object) -> bool: ...
    @override
    def __repr__(self) -> str: ...

class LazyRefType:
    def __init__(
        self,
        target: NormalizedType,
        qualifiers: Qualifier,
    ) -> None: ...
    @property
    def target(self) -> NormalizedType: ...
    @property
    def qualifiers(self) -> Qualifier: ...
    def _replace_child(self, old: object, new: NormalizedType) -> None: ...
    @override
    def __eq__(self, other: object) -> bool: ...
    @override
    def __repr__(self) -> str: ...

type NormalizedType = (
    SentinelType
    | TypeVarType
    | ParamSpecType
    | PlainType
    | ProtocolType
    | TypedDictType
    | UnionType
    | CallableType
    | LazyRefType
)

class CyclePlaceholder:
    def __init__(self) -> None: ...

class RuleGraph:
    def __init__(self, root: object) -> None: ...

class Registry:
    def __init__(self, registry: object) -> None: ...
    def compile(
        self,
        rules: RuleGraph,
        target: NormalizedType,
        *,
        solver_fixpoint_iteration_limit: int = 1024,
        solver_stack_depth_limit: int = 1024,
    ) -> object: ...
