name: Publish

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      testpypi:
        description: Publish to TestPyPI
        type: boolean
        default: true

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: publish
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Publish package
        uses: PyO3/maturin-action@v1
        env:
          MATURIN_REPOSITORY_URL: ${{ github.event_name == 'workflow_dispatch' && inputs.testpypi && 'https://test.pypi.org/legacy/' || 'https://upload.pypi.org/legacy/' }}
        with:
          command: publish
          args: --release --locked --sdist --compatibility pypi -i python3.14
          manylinux: "2014"
          rust-toolchain: stable
