name: Publish

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: publish
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Publish to PyPI
        uses: PyO3/maturin-action@v1
        with:
          command: publish
          args: --release --locked --sdist --compatibility pypi -i python3.14
          manylinux: "2014"
          rust-toolchain: stable
